CREATE TABLE IF NOT EXISTS checklist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tugas VARCHAR(255),
  bulan VARCHAR(20),
  minggu INT,
  status TINYINT(1) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  tanggal DATE
);

ALTER TABLE checklist 
  CHANGE COLUMN tugas item VARCHAR(255),
  ADD COLUMN bulan VARCHAR(20),
  ADD COLUMN minggu INT,
  CHANGE COLUMN status status TINYINT(1) DEFAULT 0,
  ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;


ALTER TABLE checklist ADD COLUMN tanggal DATE;