-- Create database checklist_pegawai
CREATE DATABASE IF NOT EXISTS checklist_pegawai;
USE checklist_pegawai;

-- Create checklist table
CREATE TABLE IF NOT EXISTS checklist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  tanggal DATE NOT NULL,
  tugas TEXT NOT NULL,
  status ENUM('done', 'not_done') NOT NULL DEFAULT 'not_done'
);

-- Insert initial data based on data.js
INSERT INTO checklist (nama, tanggal, tugas, status) VALUES 
('Retno Widhi', '2025-04-18', 'Input SAP', 'not_done'),
('Retno Widhi', '2025-04-18', 'Input Data monitoring pengadaan dan pembelian lokal Kebun di link', 'not_done'),
('Retno Widhi', '2025-04-18', 'Membuat AU31A Bahan setiap Triwulan permintaan PPAP', 'not_done'),
('Retno Widhi', '2025-04-18', 'Membuat Surat permintaan Pinjam Pakai Bahan dll di Nadine', 'not_done'),
('Retno Widhi', '2025-04-18', 'Cek Daftar Upah dari Afdeling', 'not_done'),
('Retno Widhi', '2025-04-18', 'Cek Buku Administrasi Afdeling', 'not_done'),
('Retno Widhi', '2025-04-18', 'Input Data Monitoring Sewa Kendaraan', 'not_done'),
('Retno Widhi', '2025-04-18', 'Stok Opname Bahan Gudang', 'not_done'),
('Retno Widhi', '2025-04-18', 'Input Data PADI UMKM', 'not_done'),
('Retno Widhi', '2025-04-18', 'Input Data AU31A ke Aplikasi IPS', 'not_done'),

('Sugihartono', '2025-04-18', 'Melayani pengambilan barang', 'not_done'),
('Sugihartono', '2025-04-18', 'Mengisi kartu 56 K', 'not_done'),
('Sugihartono', '2025-04-18', 'Mengisi kartu 54 K', 'not_done'),
('Sugihartono', '2025-04-18', 'Membuat Surat Pengeluaran', 'not_done'),
('Sugihartono', '2025-04-18', 'Pengambilan barang Dari gudang Wilayah', 'not_done'),
('Sugihartono', '2025-04-18', 'Pengambilan barang Dari Mitra', 'not_done'),
('Sugihartono', '2025-04-18', 'Pengambilan barang Dari Kebun Luar', 'not_done'),
('Sugihartono', '2025-04-18', 'Membuat BA Penerimaan Barang Masuk', 'not_done'),
('Sugihartono', '2025-04-18', 'Stock Opname Barang', 'not_done'),
('Sugihartono', '2025-04-18', 'Mengukur Penerimaan Kayu', 'not_done'),
('Sugihartono', '2025-04-18', 'Membuat BA Penerimaan', 'not_done'),
('Sugihartono', '2025-04-18', 'Pengecekan Buku-Buku Afdeling', 'not_done'),

('Handik Rohman Yanto', '2025-04-18', 'Laporan / isi spreadsheet HKO dan estimasi produksi ke Kanreg', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cek pengambilan DRC TPH', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cek Sadap Tuntas', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cek Hasil Timbangan di TPH', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cek Penerimaan Latek di Pabrik/DRC', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Rekap hasil Produksi', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cocokan Hasil Produksi Pabrik Vs Afdeling', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Laporan / isi spreadsheet Real HKO dan Produksi ke Kanreg', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cek Buku Apresiasi Mandor 1, Mandor, Tap Control', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Rekap Format 1-7', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Isian Spreadsheet Evaluasi Stimual Kanreg', 'not_done'),
('Handik Rohman Yanto', '2025-04-18', 'Cek Buku - Buku Administrasi Afdeling Pabrik', 'not_done'),

('Budi Hariyono', '2025-04-18', 'Input Produksi Harian Kayu', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Monitoring Stok dan Pemenuhan Kontrak', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Input Link Produksi Kayu 2025', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Copro SAP Produksi Kayu', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Cek Kondisi barang di TPK, Baik Panjang log Maupun Grade Diameter log', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Cek Email Nadine dan Zimbra', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Briefing teman-teman TPK mengenai Penerimaan dari Afd maupun waktu pengiriman ke pembeli', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Mengawal proses pengiriman', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Melakukan stok opname tanggal 15', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Berita acara stok opname per tanggal 15', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan berita acara ongkos per tanggal 15', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Master pencocokan penjualan kayu (SAP) akhir bulan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Melakukan stok opname akhir bulan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Berita acara stok opname akhir bulan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan berita acara ongkos akhir bulan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan Berita acara selesai panen', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pencocokan faktur pajak dengan bagian Fico (Gayuh)', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pencocokan faktur pajak dengan bagian HCM (Rahmi)', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan data pendapatan per komoditi per bulan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan laporan PB 26 K Kayu log', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan laporan PB 26.1 K Kayu log', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Kirim form monitoring pajak keluaran Coretax', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan dokumen kontrak, Delivery Order', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Realisasi penjualan jika kontrak sudah selesai', 'not_done'),
('Budi Hariyono', '2025-04-18', 'BA penyelesaian kontrak', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan Surat Perintah Kerja (SPK)', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan berita acara afkir', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan surat permohonan penjualan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan faktur pajak keluaran Coretax', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pencocokan pembayaran dengan bagian KSO (Widodo)', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan Billing Revenue (BR)/pengakuan pendapatan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Verifikasi Afdeling Sumber Waringin', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Kirim Form Permintaan Sales Order (SO) kepada Bagian MAP', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan DO SAP setiap ada pengiriman', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan BR SAP setiap ada pengiriman', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan surat pengiriman kayu ke Mitra', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Mengirim bahan Ongkos TMA ke bagian HCM (Rahmi)', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan surat potensi bebas kontrak per Triwulan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Pembuatan surat Counter dan Negosiasi penjualan', 'not_done'),
('Budi Hariyono', '2025-04-18', 'Arsip dan bendel Dokumen penjualan', 'not_done'),

('Gayuh A.F.', '2025-04-18', 'Membuat Kas SUPERMAN', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Input KAS dan BANK ke SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Ambil Alih Biaya pada RK SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Input SAP (Pendapatan Agro dan Pendapatan Kayu)', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuat Buku Besar KAS dan BANK', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuat BA Tutup Masa KAS dan BANK', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Memasukan Bukti Kas ke Outner', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuat LM 14 2 dan ZLEGAL Analyss', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Menarik Data Analis LM 27 LM 13 Karet LM 13 Kayu dan LM 16', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Cek neraca dan biaya di SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuku Premi di SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuku BPJS-KS di SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuku PPH (21 23 4 ayat 2) di SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Clearing Pedapatan (KSO Kayu dan Agrowisata) di SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Settle closing SAP', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Koordinasi dengan Kantor Regional 5', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Membuat Peta Gis', 'not_done'),
('Gayuh A.F.', '2025-04-18', 'Permintaan Data dari Kantor Regional 5', 'not_done'),

('Angga Wahyuningtyas', '2025-04-18', 'Upload BKM', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Cocokan Rp BKM Hi vs LH', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat reservasi bon2an tanaman MB 21', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat pengeluaran barang ( Good Issue )', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Menghimpun sadap Pembelian', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat pengajuan Modal Kerja ( Setiap masa 1 2 dan 3 )', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat rekapan sadap tunai setiap masa 1 dan 3', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Pencocokan rekapan sadap tunai setiap masa 1 dan 3', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat rekapan upah setiap masa 1 dan 3', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Pencocokan upah ( DU) vs BKM global', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Pencocokan Kg produksi dan Rp dari DU vs BKM', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengarsip Upah per masa', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengarsip DU tunai', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Menghimpun program kerja ( buat otorisasi bulan berikutnya )', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat Jadwal Pemantauan IMS ( VO6 001)', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Melaksanakan Pemantauan IMS  ( V06 002)', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Melaksanakan Pemantauan Program IMS  ( V06 003)', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Pelaporan Interen Ke Manager dan sekper dan hukum Reg 5', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat rekapan premi KHL Kantor', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Update pohon aneka kayu dan  karet ( SAP )', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Update sasaran mutu sasaran lingkungan dan program lingkungan', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Verifikasi administrasi Afd. Dampar', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V06 001 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 002 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 003 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 004 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 005 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 006 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 007 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 008 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 009 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 010 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengerjakan V01 011 IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Aspek Penting Lingkungan', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Sasaran K3', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Sasaran Lingkungan', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Sasaran Mutu', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Program Manajemen Lingkungan', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Membuat projec ( kalau ada TTI )', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengisi isian spreadsheet IMS', 'not_done'),
('Angga Wahyuningtyas', '2025-04-18', 'Mengisi pengajuan moker khusus tunai dan realisasi', 'not_done'),

('Agung Aditya', '2025-04-18', 'Memeriksa semua pengeluaran langsung sebelum menjadi kas', 'not_done'),
('Agung Aditya', '2025-04-18', 'Memeriksa bukti kas masuk dan keluar', 'not_done'),
('Agung Aditya', '2025-04-18', 'Memeriksa buku kas harian', 'not_done'),
('Agung Aditya', '2025-04-18', 'Memeriksa buku kas 10 harian per masa', 'not_done'),
('Agung Aditya', '2025-04-18', 'melakukan kas opname setiap akhir bulan', 'not_done'),
('Agung Aditya', '2025-04-18', 'Menyiapkan kebutuhan permintaan modal kerja secara periodik', 'not_done'),
('Agung Aditya', '2025-04-18', 'Merencanakan pembayaran gaji dan upah karyawan', 'not_done'),
('Agung Aditya', '2025-04-18', 'Memeriksa pengajuan permintaan bahan dan barang', 'not_done'),
('Agung Aditya', '2025-04-18', 'Melaksanakan stock opname persediaan bahan dan barang', 'not_done'),
('Agung Aditya', '2025-04-18', 'Memeriksa pengajuan permintaan bahan dan barang Agrowisata', 'not_done'),
('Agung Aditya', '2025-04-18', 'Memeriksa laporan keuangan agrowisata (pendapatan dan biayaMenjalankan tugas khusus dari atasanMelakukan pembinaan dan pemgembangan SDM)', 'not_done'),
('Agung Aditya', '2025-04-18', 'Support dan motivasi', 'not_done'),
('Agung Aditya', '2025-04-18', 'Melakukan penilaian kinerja/evaluasi', 'not_done'),

('Nuraeni', '2025-04-18', 'Pembuatan surat', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan daftar upah karyawan karpim & karpel (Potongan, Premi)', 'not_done'),
('Nuraeni', '2025-04-18', 'Laporan Pensiunan dan BPJS Kesehatan Pensiunan', 'not_done'),
('Nuraeni', '2025-04-18', 'Foto SKD Pensiunan', 'not_done'),
('Nuraeni', '2025-04-18', 'Setaiap (April-Juli) dan (Oktober - Desember)', 'not_done'),
('Nuraeni', '2025-04-18', 'BPJS Ketenagakerjaan', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan Permintaan Kanreg', 'not_done'),
('Nuraeni', '2025-04-18', 'Terima tamu dari instansi lain', 'not_done'),
('Nuraeni', '2025-04-18', 'Kroscek buku kas Golf & GAS', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan payroll karyawan karpim & karpel', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan THR & BHR', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan Tanggungan karyawan kepada perusahaan', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan laporan pengosongan rumah dinas', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan Bonus, remonerasi dll', 'not_done'),
('Nuraeni', '2025-04-18', 'Memasukkan BBD', 'not_done'),
('Nuraeni', '2025-04-18', 'Mempersiapkan segala sesuatu klo ada rapat/pertemuan', 'not_done'),
('Nuraeni', '2025-04-18', 'Kroscek Buku afdeling', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan LKS Bipartit', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan PHI', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan Penilaian Karyawan APMS', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan data personalia', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan dan membayar kary yang menerima SHT dll', 'not_done'),
('Nuraeni', '2025-04-18', 'Mengerjakan permintaan Disnaker', 'not_done'),
('Nuraeni', '2025-04-18', 'SP.Bun', 'not_done'),
('Nuraeni', '2025-04-18', 'Melaksanakan tugas tugas lain dari manajer askep astuu', 'not_done'),

('Dodo Yuono', '2025-04-18', 'Cek aplikasi Nadien/email surat masuk (bila ada surat masuk terkait KSO dari MAP)', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat tindak lanjut sesuai surat', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat SPTA online pada aplikasi  Prodis (Saat panen)', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Monitoring produksi tebu (saat panen)', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Pengecekan Daftar Upah (DU) dengan Buku potongan', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Pengecekan dan pencocokan Buku Administrasi Afd. dengan LH Akhir Bulan', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Pengecekan laporan sewa kendaraan', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Evaluasi pembayaran dan pendapatan KSO', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Monitoring profit sharing/membuat tagihan profit sharing', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat pengajuan KSO bila ada pengajuan dari mitra KSO', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Aploud dokumen pengajuan yang telah divalidasi ke Simon KSO', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Update spreedsheet monitoring KSO Bagian Tanaman Regional 5', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat surat-surat Negosiasi KSO,  ke Mitra dan MAP Regional 5', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Pengukuran areal KSO setelah ada penetapan', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Cek areal KSO Pasca tanam', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat Berita Acara hasil pengukuran areal dan Berita Acara pengecekan areal', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat Perjanjian Kerja Sama Operasional', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat surat Penagihan pembayaran KSO ke Mitra KSO', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat Berita Acara penyelesaian panen dan Berita Acara penyerahan lahan', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Scan dok. Aploud dokumen BA Ukur, PKS dan bukti pembayaran  ke Simon KSO', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Membuat surat ke Regional 5', 'not_done'),
('Dodo Yuono', '2025-04-18', 'Kunjungan ke mitra penyelesaian NKM', 'not_done'),

('Rahmi Tri Utami', '2025-04-18', 'Mengerjakan Buku Rol', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat LH', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Mengerjakan BKM', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Input BKM di SAP', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Menghimpun LH Afdeling', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat SPD', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Input BPD', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat pengajuan modal kerja KHL', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Menyiapkan pengajuan premi KHL dan potongan koperasi KHL', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat Daftar Upah KHL', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat Slip Gaji KHL', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Menyiapkan Natura Karyawan', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Input Potongan dan Premi Afdeling di Checkroll', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Posting Checkroll', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat Slip Gaji Kartap', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat Kontribusi BUMN Pajak', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Menyiapkan bukti potong PPh 21 23 dan 4 ayat2', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Lapor Pajak pph 21 23 dan 4 ayat 2', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Mengecek DU afdeling', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Mengecek Administrasi afdeling', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Stock Opnam Kayu', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat LU8 DIKLAT', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Menghimpun DU Afdeling', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Mengerjakan LM 67 KHL', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Membuat bon barang', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Foto SKD Pensiunan', 'not_done'),
('Rahmi Tri Utami', '2025-04-18', 'Mengecek bukti potong per karyawan untuk pph 21', 'not_done'),

('Endar Setyo Budi', '2025-04-18', 'Input data LHP per mutu dilink Bagian Tanaman Regional 5', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Buat faktur pengiriman produksi Sheet', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Monitoring proses pengiriman produksi Sheet', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Buat faktur dan monitoring proses pengiriman produksi lump GT & Limbah', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Input data monitoring pemeliharaan kayu dilink HO', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Input data inventaris aneka kayu TP dan TDP dilink HO', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Input data inventaris KSO kayu KTI dilink Bagian Tanaman Regional 5', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Stock opname produksi pabrik', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Cek buku-buku administrasi Afdeling Kalibajing', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Input nilai buku aneka kayu TP dan TDP dilink HO', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Mengerjakan KKJ COPRO produksi per mutu', 'not_done'),
('Endar Setyo Budi', '2025-04-18', 'Input SAP Produksi Karet', 'not_done'),

('Purwanto', '2025-04-18', 'Kroscek inputan produksi antara PB39 & PB40 dengan inputan afdeling', 'not_done'),
('Purwanto', '2025-04-18', 'Input curah hujan dari afdeling ke link KanReg', 'not_done'),
('Purwanto', '2025-04-18', 'Input produksi super infer link KanReg', 'not_done'),
('Purwanto', '2025-04-18', 'Memastikan spreadsheet diisi afdeling', 'not_done'),
('Purwanto', '2025-04-18', 'Bulanan/Mingguan/Masa', 'not_done'),
('Purwanto', '2025-04-18', 'Menyiapkan data per tapper masa I (challenge)', 'not_done'),
('Purwanto', '2025-04-18', 'Stock Opname produksi karet', 'not_done'),
('Purwanto', '2025-04-18', 'Dropping moker ke afdeling', 'not_done'),
('Purwanto', '2025-04-18', 'Mengecek buku himpunan afdeling (pendampingan admnistrasi afdeling)', 'not_done'),
('Purwanto', '2025-04-18', 'Membuat google drive ( Produksi per TT Produksi per penyadap Evaluasi Stimulansia CH)', 'not_done'),
('Purwanto', '2025-04-18', 'Mutasi areal per bulan', 'not_done'),
('Purwanto', '2025-04-18', 'Input produksi dan HKO per TT LM52 LM 53 ke link KanReg', 'not_done'),
('Purwanto', '2025-04-18', 'Input biaya per penyadap ke link KanReg', 'not_done'),
('Purwanto', '2025-04-18', 'Input PICA Karet ke link KanReg', 'not_done'),
('Purwanto', '2025-04-18', 'Himpun program kerja dari afdeling menjadi Otorisasi', 'not_done'),
('Purwanto', '2025-04-18', 'Selayang Pandang', 'not_done'),
('Purwanto', '2025-04-18', 'Menghimpun LM (Laporan Manajemen)', 'not_done'),
('Purwanto', '2025-04-18', 'Menghimpun PPAP (Permintaan Pelaksanaan Anggaran Perusahaan)', 'not_done'),
('Purwanto', '2025-04-18', 'Menghimpun RKAP (Rencana Kebutuhan Anggaran Perusahaan)', 'not_done'),
('Purwanto', '2025-04-18', 'Buat surat/Memo hal tanaman karet ke Afdeling/KanReg', 'not_done'),
('Purwanto', '2025-04-18', 'Operator evaluasi kinerja', 'not_done'),
('Purwanto', '2025-04-18', 'Menyiapkan bahan rapat zoom meeting terkait kebun entres', 'not_done'),
('Purwanto', '2025-04-18', 'Menyiapkan bahan rapat zoom meeting terkait evaluasi kinerja', 'not_done'),
('Purwanto', '2025-04-18', 'Gotong royong pekerjaan cuci getah tanah di pabrik', 'not_done'),
('Purwanto', '2025-04-18', 'Mendampingi treatment pekerjaan bulan Maret dengan Krani afdeling', 'not_done'),
('Purwanto', '2025-04-18', 'Menghimpun evaluasi')
